// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYYwaADLY-HeX_b7RPlrstNCoXwSuXD0',
    appId: '1:1025957601476:web:eb880f9a0a3181d0162991',
    messagingSenderId: '1025957601476',
    projectId: 'fitnesh-f1592',
    authDomain: 'fitnesh-f1592.firebaseapp.com',
    storageBucket: 'fitnesh-f1592.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr782XQG25rfHsfB6chr5jjbsjdvOKyzI',
    appId: '1:1025957601476:android:2d3d6d0b8a215539162991',
    messagingSenderId: '1025957601476',
    projectId: 'fitnesh-f1592',
    storageBucket: 'fitnesh-f1592.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_jyvX0jVN6cjitBYnGmqS1qZ0luIAjis',
    appId: '1:1025957601476:ios:3630a1708097f19d162991',
    messagingSenderId: '1025957601476',
    projectId: 'fitnesh-f1592',
    storageBucket: 'fitnesh-f1592.appspot.com',
    iosClientId: '1025957601476-kpkofr6r4rvbhds8rhfn2ucg3f7er6ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_jyvX0jVN6cjitBYnGmqS1qZ0luIAjis',
    appId: '1:1025957601476:ios:d0ebb11d96f52744162991',
    messagingSenderId: '1025957601476',
    projectId: 'fitnesh-f1592',
    storageBucket: 'fitnesh-f1592.appspot.com',
    iosClientId: '1025957601476-k55kd2h13c9mmu0qhktccr85fsg2qbq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesh.RunnerTests',
  );
}
